#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X 
bspc monitor HDMI-2 -d ON OFF

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 1
bspc config focused_border_color "#F0F0F0"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D

killall polybar
killall picom
killall mpv 

picom &
xsetroot -cursor_name left_ptr

xwinwrap -g 1920x1080+0+0 -ov -ni -- mpv -wid WID -loop ~/.config/wallpaper.gif & 
xwinwrap -g 1920x1080+1920+0 -ov -ni -- mpv -wid WID -loop ~/.config/wallpaper.gif & 

exec $HOME/.config/polybar/launch.sh
